### ISSUE TITLE
Write "go together" relation

### ISSUE THREAD

**Issue by Aurora1024** [dev-ops-recommendation/recommendations#9] opened 2021-06-21 20:15 UTC
As a Developer
I need to store all "go together" relationship from orders
So that I can count the frequency of all "go together" products

Assumptions

The "go together" Relation DB has following columns
Product1_Id
Product2_Id
Frequency

Acceptance Criteria
Given a sequence of Product_Id, Product_Id
When the product pair exist in the "go together" Relation DB
Then the Frequency of the pair add 1

Given a sequence of Product_Id, Product_Id
When the product pair not exist in the "go together" Relation DB
Then the The "go together" Relation DB add one row with the given Product_Id pair and Frequency as 1

**Comment by mandy-cmd** [comment] 2021-06-24 01:28
Closed as duplicate of https://github.com/dev-ops-recommendation/recommendations/issues/18

**Closed as completed by mandy-cmd** 2021-06-24 01:28 UTC
Labels: enhancement
